DO $stage$
DECLARE p jsonb := $payload${"events":[{"slug":"victoria-park-5k-10k-half-marathon-january","name":"Victoria Park 5K, 10K & Half Marathon","sport":"Running","country":"England","county":"South of England","city":"Tower Hamlets","distances":["Half"]},{"slug":"brighten","name":"BrighTEN","sport":"Running","country":"England","county":"South of England","city":"Brighton","distances":["10mi"]},{"slug":"queen-elizabeth-off-road-half-marathon-march","name":"Queen Elizabeth Country Park Trail Run 2027","sport":"Running","country":"England","county":"Hampshire","city":"Horndean","distances":["15K","8K"]}],"editions":[{"eventSlug":"victoria-park-5k-10k-half-marathon-january","date":"2027-01-10","distance":"Half","distanceKm":21.0975,"status":"TBC","source":"https://runabc.co.uk/victoria-park-5k-10k-half-marathon-january","startTime":null,"notes":"Date and distance checked on 11 September 2026 for the RunRecs UK October 2026–January 2027 audit. Entry availability not verified."},{"eventSlug":"brighten","date":"2027-01-17","distance":"10mi","distanceKm":16.09344,"status":"TBC","source":"https://runabc.co.uk/brighten","startTime":null,"notes":"Date and distance checked on 11 September 2026 for the RunRecs UK October 2026–January 2027 audit. Entry availability not verified."},{"eventSlug":"queen-elizabeth-off-road-half-marathon-march","date":"2027-01-30","distance":"15K","distanceKm":15.0,"status":"TBC","source":"https://runabc.co.uk/queen-elizabeth-off-road-half-marathon-march","startTime":null,"notes":"Date and distance checked on 11 September 2026 for the RunRecs UK October 2026–January 2027 audit. Entry availability not verified."},{"eventSlug":"queen-elizabeth-off-road-half-marathon-march","date":"2027-01-30","distance":"8K","distanceKm":8.0,"status":"TBC","source":"https://runabc.co.uk/queen-elizabeth-off-road-half-marathon-march","startTime":null,"notes":"Date and distance checked on 11 September 2026 for the RunRecs UK October 2026–January 2027 audit. Entry availability not verified."}]}$payload$::jsonb;
BEGIN
 INSERT INTO catalogue_import_batches(id,source_key,source_url,payload_hash,payload,submitted_by)
 VALUES ('b5c26c6d-5ace-5591-9f82-6175d06786a1','runrecs:uk:0-100km:2026-10-01:2027-01-31:part-4','https://runabc.co.uk/races/10/2026','706c4e0549df89a42c2b052b6736a17e05abbb6b3b395d24e1015d5952c8366f',p,'paultwbrowne@gmail.com');
 INSERT INTO catalogue_staged_rows(batch_id,row_type,row_number,natural_key,payload)
 SELECT 'b5c26c6d-5ace-5591-9f82-6175d06786a1','event',ordinality::int,value->>'slug',value FROM jsonb_array_elements(p->'events') WITH ORDINALITY;
 INSERT INTO catalogue_staged_rows(batch_id,row_type,row_number,natural_key,payload)
 SELECT 'b5c26c6d-5ace-5591-9f82-6175d06786a1','edition',ordinality::int,concat_ws('|',value->>'eventSlug',value->>'date',value->>'distance'),value FROM jsonb_array_elements(p->'editions') WITH ORDINALITY;
END $stage$;