-- Register a non-crawlable provenance source for fixtures entered manually by
-- an approved staff reviewer. It exists only so every private candidate retains
-- a source ID; it can never enter the crawl queue.

insert into managed_fixture_sources (
  source_id,
  source_name,
  start_url,
  canonical_start_url,
  source_type,
  requested_enabled,
  enabled,
  source_section,
  region_scope,
  country_focus,
  coverage_scope,
  coverage_start_year,
  coverage_end_year,
  surface_scope,
  timing_scope,
  chip_timed_status,
  permission_url,
  allowed_domains,
  race_link_include_regex,
  race_link_exclude_regex,
  profile,
  follow_history_links,
  max_pages,
  rate_limit_seconds,
  rights_status,
  notes,
  review_status,
  duplicate_status,
  duplicate_note,
  imported_by,
  reviewed_by,
  reviewed_at,
  review_note
) values (
  'manual_staff_research',
  'Manual ATHRECS staff research',
  'https://www.athrecs.com/admin/verification',
  'https://athrecs.com/admin/verification',
  'directory',
  false,
  false,
  'Staff research',
  'Global',
  'Global',
  'Past | Present | Future',
  null,
  null,
  'All reviewed sports',
  'Manual verification only',
  'Not applicable',
  null,
  'athrecs.com|www.athrecs.com',
  null,
  null,
  'manual_staff_research',
  false,
  1,
  60,
  'Manual research only',
  'Internal provenance row. Never crawl; every event fact, official website and provider still requires the normal manual verification gate.',
  'manual_only',
  'new',
  'System-managed internal provenance source',
  'system',
  'system',
  now(),
  'Created by migration for attributed manual candidate staging'
)
on conflict (source_id) do nothing;
