/**
 * Collection areas from ISO 3166-2 via pycountry 26.2.16 (checked 2026-09-12).
 * https://github.com/pycountry/pycountry
 * Separately selectable country/territory codes are excluded from parent areas.
 * AU-JBT is an application collection code for Jervis Bay, not an ISO code.
 * See docs/runrecs-collector/regions.md for sources and boundary rules.
 */
const regionEntries: Record<string, ReadonlyArray<readonly [string, string]>> = {
  US: [
    ["US-AL", "Alabama"],
    ["US-AK", "Alaska"],
    ["US-AZ", "Arizona"],
    ["US-AR", "Arkansas"],
    ["US-CA", "California"],
    ["US-CO", "Colorado"],
    ["US-CT", "Connecticut"],
    ["US-DE", "Delaware"],
    ["US-DC", "District of Columbia"],
    ["US-FL", "Florida"],
    ["US-GA", "Georgia"],
    ["US-HI", "Hawaii"],
    ["US-ID", "Idaho"],
    ["US-IL", "Illinois"],
    ["US-IN", "Indiana"],
    ["US-IA", "Iowa"],
    ["US-KS", "Kansas"],
    ["US-KY", "Kentucky"],
    ["US-LA", "Louisiana"],
    ["US-ME", "Maine"],
    ["US-MD", "Maryland"],
    ["US-MA", "Massachusetts"],
    ["US-MI", "Michigan"],
    ["US-MN", "Minnesota"],
    ["US-MS", "Mississippi"],
    ["US-MO", "Missouri"],
    ["US-MT", "Montana"],
    ["US-NE", "Nebraska"],
    ["US-NV", "Nevada"],
    ["US-NH", "New Hampshire"],
    ["US-NJ", "New Jersey"],
    ["US-NM", "New Mexico"],
    ["US-NY", "New York"],
    ["US-NC", "North Carolina"],
    ["US-ND", "North Dakota"],
    ["US-OH", "Ohio"],
    ["US-OK", "Oklahoma"],
    ["US-OR", "Oregon"],
    ["US-PA", "Pennsylvania"],
    ["US-RI", "Rhode Island"],
    ["US-SC", "South Carolina"],
    ["US-SD", "South Dakota"],
    ["US-TN", "Tennessee"],
    ["US-TX", "Texas"],
    ["US-UT", "Utah"],
    ["US-VT", "Vermont"],
    ["US-VA", "Virginia"],
    ["US-WA", "Washington"],
    ["US-WV", "West Virginia"],
    ["US-WI", "Wisconsin"],
    ["US-WY", "Wyoming"],
  ],
  CA: [
    ["CA-AB", "Alberta"],
    ["CA-BC", "British Columbia"],
    ["CA-MB", "Manitoba"],
    ["CA-NB", "New Brunswick"],
    ["CA-NL", "Newfoundland and Labrador"],
    ["CA-NT", "Northwest Territories"],
    ["CA-NS", "Nova Scotia"],
    ["CA-NU", "Nunavut"],
    ["CA-ON", "Ontario"],
    ["CA-PE", "Prince Edward Island"],
    ["CA-QC", "Quebec"],
    ["CA-SK", "Saskatchewan"],
    ["CA-YT", "Yukon"],
  ],
  AU: [
    ["AU-ACT", "Australian Capital Territory"],
    ["AU-JBT", "Jervis Bay Territory"],
    ["AU-NSW", "New South Wales"],
    ["AU-NT", "Northern Territory"],
    ["AU-QLD", "Queensland"],
    ["AU-SA", "South Australia"],
    ["AU-TAS", "Tasmania"],
    ["AU-VIC", "Victoria"],
    ["AU-WA", "Western Australia"],
  ],
  IN: [
    ["IN-AN", "Andaman and Nicobar Islands"],
    ["IN-AP", "Andhra Pradesh"],
    ["IN-AR", "Arunachal Pradesh"],
    ["IN-AS", "Assam"],
    ["IN-BR", "Bihar"],
    ["IN-CH", "Chandigarh"],
    ["IN-CG", "Chhattisgarh"],
    ["IN-DH", "Dadra and Nagar Haveli and Daman and Diu"],
    ["IN-DL", "Delhi"],
    ["IN-GA", "Goa"],
    ["IN-GJ", "Gujarat"],
    ["IN-HR", "Haryana"],
    ["IN-HP", "Himachal Pradesh"],
    ["IN-JK", "Jammu and Kashmir"],
    ["IN-JH", "Jharkhand"],
    ["IN-KA", "Karnataka"],
    ["IN-KL", "Kerala"],
    ["IN-LA", "Ladakh"],
    ["IN-LD", "Lakshadweep"],
    ["IN-MP", "Madhya Pradesh"],
    ["IN-MH", "Maharashtra"],
    ["IN-MN", "Manipur"],
    ["IN-ML", "Meghalaya"],
    ["IN-MZ", "Mizoram"],
    ["IN-NL", "Nagaland"],
    ["IN-OD", "Odisha"],
    ["IN-PY", "Puducherry"],
    ["IN-PB", "Punjab"],
    ["IN-RJ", "Rajasthan"],
    ["IN-SK", "Sikkim"],
    ["IN-TN", "Tamil Nadu"],
    ["IN-TS", "Telangana"],
    ["IN-TR", "Tripura"],
    ["IN-UP", "Uttar Pradesh"],
    ["IN-UK", "Uttarakhand"],
    ["IN-WB", "West Bengal"],
  ],
  CN: [
    ["CN-AH", "Anhui"],
    ["CN-BJ", "Beijing"],
    ["CN-CQ", "Chongqing"],
    ["CN-FJ", "Fujian"],
    ["CN-GS", "Gansu"],
    ["CN-GD", "Guangdong"],
    ["CN-GX", "Guangxi"],
    ["CN-GZ", "Guizhou"],
    ["CN-HI", "Hainan"],
    ["CN-HE", "Hebei"],
    ["CN-HL", "Heilongjiang"],
    ["CN-HA", "Henan"],
    ["CN-HB", "Hubei"],
    ["CN-HN", "Hunan"],
    ["CN-NM", "Inner Mongolia"],
    ["CN-JS", "Jiangsu"],
    ["CN-JX", "Jiangxi"],
    ["CN-JL", "Jilin"],
    ["CN-LN", "Liaoning"],
    ["CN-NX", "Ningxia"],
    ["CN-QH", "Qinghai"],
    ["CN-SN", "Shaanxi"],
    ["CN-SD", "Shandong"],
    ["CN-SH", "Shanghai"],
    ["CN-SX", "Shanxi"],
    ["CN-SC", "Sichuan"],
    ["CN-TJ", "Tianjin"],
    ["CN-XZ", "Tibet (Xizang)"],
    ["CN-XJ", "Xinjiang"],
    ["CN-YN", "Yunnan"],
    ["CN-ZJ", "Zhejiang"],
  ],
  RU: [
    ["RU-AD", "Adygeya, Respublika"],
    ["RU-AL", "Altay, Respublika"],
    ["RU-ALT", "Altayskiy kray"],
    ["RU-AMU", "Amurskaya oblast'"],
    ["RU-ARK", "Arkhangel'skaya oblast'"],
    ["RU-AST", "Astrakhanskaya oblast'"],
    ["RU-BA", "Bashkortostan, Respublika"],
    ["RU-BEL", "Belgorodskaya oblast'"],
    ["RU-BRY", "Bryanskaya oblast'"],
    ["RU-BU", "Buryatiya, Respublika"],
    ["RU-CE", "Chechenskaya Respublika"],
    ["RU-CHE", "Chelyabinskaya oblast'"],
    ["RU-CHU", "Chukotskiy avtonomnyy okrug"],
    ["RU-CU", "Chuvashskaya Respublika"],
    ["RU-DA", "Dagestan, Respublika"],
    ["RU-IN", "Ingushetiya, Respublika"],
    ["RU-IRK", "Irkutskaya oblast'"],
    ["RU-IVA", "Ivanovskaya oblast'"],
    ["RU-KB", "Kabardino-Balkarskaya Respublika"],
    ["RU-KGD", "Kaliningradskaya oblast'"],
    ["RU-KL", "Kalmykiya, Respublika"],
    ["RU-KLU", "Kaluzhskaya oblast'"],
    ["RU-KAM", "Kamchatskiy kray"],
    ["RU-KC", "Karachayevo-Cherkesskaya Respublika"],
    ["RU-KR", "Kareliya, Respublika"],
    ["RU-KEM", "Kemerovskaya oblast'"],
    ["RU-KHA", "Khabarovskiy kray"],
    ["RU-KK", "Khakasiya, Respublika"],
    ["RU-KHM", "Khanty-Mansiyskiy avtonomnyy okrug"],
    ["RU-KIR", "Kirovskaya oblast'"],
    ["RU-KO", "Komi, Respublika"],
    ["RU-KOS", "Kostromskaya oblast'"],
    ["RU-KDA", "Krasnodarskiy kray"],
    ["RU-KYA", "Krasnoyarskiy kray"],
    ["RU-KGN", "Kurganskaya oblast'"],
    ["RU-KRS", "Kurskaya oblast'"],
    ["RU-LEN", "Leningradskaya oblast'"],
    ["RU-LIP", "Lipetskaya oblast'"],
    ["RU-MAG", "Magadanskaya oblast'"],
    ["RU-ME", "Mariy El, Respublika"],
    ["RU-MO", "Mordoviya, Respublika"],
    ["RU-MOW", "Moscow"],
    ["RU-MOS", "Moskovskaya oblast'"],
    ["RU-MUR", "Murmanskaya oblast'"],
    ["RU-NEN", "Nenetskiy avtonomnyy okrug"],
    ["RU-NIZ", "Nizhegorodskaya oblast'"],
    ["RU-NGR", "Novgorodskaya oblast'"],
    ["RU-NVS", "Novosibirskaya oblast'"],
    ["RU-OMS", "Omskaya oblast'"],
    ["RU-ORE", "Orenburgskaya oblast'"],
    ["RU-ORL", "Orlovskaya oblast'"],
    ["RU-PNZ", "Penzenskaya oblast'"],
    ["RU-PER", "Permskiy kray"],
    ["RU-PRI", "Primorskiy kray"],
    ["RU-PSK", "Pskovskaya oblast'"],
    ["RU-ROS", "Rostovskaya oblast'"],
    ["RU-RYA", "Ryazanskaya oblast'"],
    ["RU-SA", "Saha, Respublika"],
    ["RU-SPE", "Saint Petersburg"],
    ["RU-SAK", "Sakhalinskaya oblast'"],
    ["RU-SAM", "Samarskaya oblast'"],
    ["RU-SAR", "Saratovskaya oblast'"],
    ["RU-SE", "Severnaya Osetiya, Respublika"],
    ["RU-SMO", "Smolenskaya oblast'"],
    ["RU-STA", "Stavropol'skiy kray"],
    ["RU-SVE", "Sverdlovskaya oblast'"],
    ["RU-TAM", "Tambovskaya oblast'"],
    ["RU-TA", "Tatarstan, Respublika"],
    ["RU-TOM", "Tomskaya oblast'"],
    ["RU-TUL", "Tul'skaya oblast'"],
    ["RU-TVE", "Tverskaya oblast'"],
    ["RU-TYU", "Tyumenskaya oblast'"],
    ["RU-TY", "Tyva, Respublika"],
    ["RU-UD", "Udmurtskaya Respublika"],
    ["RU-ULY", "Ul'yanovskaya oblast'"],
    ["RU-VLA", "Vladimirskaya oblast'"],
    ["RU-VGG", "Volgogradskaya oblast'"],
    ["RU-VLG", "Vologodskaya oblast'"],
    ["RU-VOR", "Voronezhskaya oblast'"],
    ["RU-YAN", "Yamalo-Nenetskiy avtonomnyy okrug"],
    ["RU-YAR", "Yaroslavskaya oblast'"],
    ["RU-YEV", "Yevreyskaya avtonomnaya oblast'"],
    ["RU-ZAB", "Zabaykal'skiy kray"],
  ],
  BR: [
    ["BR-AC", "Acre"],
    ["BR-AL", "Alagoas"],
    ["BR-AP", "Amapá"],
    ["BR-AM", "Amazonas"],
    ["BR-BA", "Bahia"],
    ["BR-CE", "Ceará"],
    ["BR-DF", "Distrito Federal"],
    ["BR-ES", "Espírito Santo"],
    ["BR-GO", "Goiás"],
    ["BR-MA", "Maranhão"],
    ["BR-MT", "Mato Grosso"],
    ["BR-MS", "Mato Grosso do Sul"],
    ["BR-MG", "Minas Gerais"],
    ["BR-PR", "Paraná"],
    ["BR-PB", "Paraíba"],
    ["BR-PA", "Pará"],
    ["BR-PE", "Pernambuco"],
    ["BR-PI", "Piauí"],
    ["BR-RN", "Rio Grande do Norte"],
    ["BR-RS", "Rio Grande do Sul"],
    ["BR-RJ", "Rio de Janeiro"],
    ["BR-RO", "Rondônia"],
    ["BR-RR", "Roraima"],
    ["BR-SC", "Santa Catarina"],
    ["BR-SE", "Sergipe"],
    ["BR-SP", "São Paulo"],
    ["BR-TO", "Tocantins"],
  ],
  MX: [
    ["MX-AGU", "Aguascalientes"],
    ["MX-BCN", "Baja California"],
    ["MX-BCS", "Baja California Sur"],
    ["MX-CAM", "Campeche"],
    ["MX-CHP", "Chiapas"],
    ["MX-CHH", "Chihuahua"],
    ["MX-COA", "Coahuila de Zaragoza"],
    ["MX-COL", "Colima"],
    ["MX-DUR", "Durango"],
    ["MX-GUA", "Guanajuato"],
    ["MX-GRO", "Guerrero"],
    ["MX-HID", "Hidalgo"],
    ["MX-JAL", "Jalisco"],
    ["MX-CMX", "Mexico City"],
    ["MX-MIC", "Michoacán de Ocampo"],
    ["MX-MOR", "Morelos"],
    ["MX-MEX", "México"],
    ["MX-NAY", "Nayarit"],
    ["MX-NLE", "Nuevo León"],
    ["MX-OAX", "Oaxaca"],
    ["MX-PUE", "Puebla"],
    ["MX-QUE", "Querétaro"],
    ["MX-ROO", "Quintana Roo"],
    ["MX-SLP", "San Luis Potosí"],
    ["MX-SIN", "Sinaloa"],
    ["MX-SON", "Sonora"],
    ["MX-TAB", "Tabasco"],
    ["MX-TAM", "Tamaulipas"],
    ["MX-TLA", "Tlaxcala"],
    ["MX-VER", "Veracruz de Ignacio de la Llave"],
    ["MX-YUC", "Yucatán"],
    ["MX-ZAC", "Zacatecas"],
  ],
};
export type CollectionRegion = { code: string; name: string };
export const REGIONS_BY_COUNTRY: Record<string, CollectionRegion[]> = Object.fromEntries(
  Object.entries(regionEntries).map(([country, entries]) => [
    country,
    entries.map(([code, name]) => ({ code, name })).sort((a, b) => a.name.localeCompare(b.name)),
  ]),
);
export function collectionRegions(country: string): CollectionRegion[] {
  return REGIONS_BY_COUNTRY[country] ?? [];
}
export function collectionRegion(country: string, code?: string) {
  return collectionRegions(country).find((region) => region.code === code);
}
export const REGION_BOUNDARIES: Record<string, string> = {
  US: "The United States jobs cover the 50 states and District of Columbia only. American Samoa, Guam, Northern Mariana Islands, Puerto Rico, U.S. Virgin Islands and U.S. Outlying Islands use their own country/territory jobs.",
  CN: "China jobs cover the 31 mainland province-level areas. Hong Kong (HK), Macao (MO) and Taiwan (TW) have separate collection jobs and must not be returned here.",
  AU: "Jervis Bay Territory has its own AU-JBT job; exclude it from NSW and ACT. Christmas Island, Cocos (Keeling) Islands, Norfolk Island and Heard & McDonald Islands use their own country/territory jobs.",
  RU: "Use only the listed ISO collection areas. Tyumen Oblast excludes Khanty-Mansi and Yamalo-Nenets autonomous districts; Arkhangelsk Oblast excludes Nenets autonomous district because each has its own job. Do not include Ukrainian ISO areas in Russia jobs. Unclear start-country assignments must be reported as gaps.",
};
