// Static names keep server rendering and browsers on different ICU versions identical.
export const countryNames: Readonly<Record<string, string>> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua & Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "St Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Caribbean Netherlands",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Congo - Kinshasa",
  CF: "Central African Republic",
  CG: "Congo - Brazzaville",
  CH: "Switzerland",
  CI: "Côte d’Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia & South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard & McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "St Kitts & Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "St Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "St Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macau",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "St Pierre & Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestinian Territories",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena",
  SI: "Slovenia",
  SJ: "Svalbard & Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé & Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks & Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad & Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "US Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "St Vincent & the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "US Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis & Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  XK: "Kosovo",
};
const regions = new Map(
  Object.keys(countryNames).flatMap((code) => [
    [code.toLowerCase(), code],
    [countryNames[code].toLowerCase(), code],
  ]),
);
const aliases: Record<string, string> = {
  // Current country/territory sporting codes from the IOC Olympic Data Feed.
  // https://odf.olympictech.org/2024-Paris/codes/HTML/og_cc/Country.htm
  // Display aliases only: preserve the exact source nationality and provenance.
  // ANT is Antigua & Barbuda; BRN is Bahrain, while BRU is Brunei.
  // Historical/joint/neutral teams (including AIN) are not national flags.
  afg: "AF",
  aia: "AI",
  ala: "AX",
  alb: "AL",
  alg: "DZ",
  and: "AD",
  ang: "AO",
  ant: "AG",
  arg: "AR",
  arm: "AM",
  aru: "AW",
  asa: "AS",
  ata: "AQ",
  atf: "TF",
  aus: "AU",
  aut: "AT",
  aze: "AZ",
  bah: "BS",
  ban: "BD",
  bar: "BB",
  bdi: "BI",
  bel: "BE",
  ben: "BJ",
  ber: "BM",
  bes: "BQ",
  bhu: "BT",
  bih: "BA",
  biz: "BZ",
  blm: "BL",
  blr: "BY",
  bol: "BO",
  bot: "BW",
  bra: "BR",
  brn: "BH",
  bru: "BN",
  bul: "BG",
  bur: "BF",
  bvt: "BV",
  caf: "CF",
  cam: "KH",
  can: "CA",
  cay: "KY",
  cck: "CC",
  cgo: "CG",
  cha: "TD",
  chi: "CL",
  chn: "CN",
  civ: "CI",
  cmr: "CM",
  cod: "CD",
  cok: "CK",
  col: "CO",
  com: "KM",
  cpv: "CV",
  crc: "CR",
  cro: "HR",
  cub: "CU",
  cuw: "CW",
  cxr: "CX",
  cyp: "CY",
  cze: "CZ",
  den: "DK",
  dji: "DJ",
  dma: "DM",
  dom: "DO",
  ecu: "EC",
  egy: "EG",
  eri: "ER",
  esa: "SV",
  esh: "EH",
  esp: "ES",
  est: "EE",
  eth: "ET",
  fij: "FJ",
  fin: "FI",
  flk: "FK",
  fra: "FR",
  fro: "FO",
  fsm: "FM",
  gab: "GA",
  gam: "GM",
  gbr: "GB",
  gbs: "GW",
  geo: "GE",
  geq: "GQ",
  ger: "DE",
  ggy: "GG",
  gha: "GH",
  gib: "GI",
  glp: "GP",
  gre: "GR",
  grl: "GL",
  grn: "GD",
  gua: "GT",
  guf: "GF",
  gui: "GN",
  gum: "GU",
  guy: "GY",
  hai: "HT",
  hkg: "HK",
  hmd: "HM",
  hon: "HN",
  hun: "HU",
  imn: "IM",
  ina: "ID",
  ind: "IN",
  iot: "IO",
  iri: "IR",
  irl: "IE",
  irq: "IQ",
  isl: "IS",
  isr: "IL",
  isv: "VI",
  ita: "IT",
  ivb: "VG",
  jam: "JM",
  jer: "JE",
  jor: "JO",
  jpn: "JP",
  kaz: "KZ",
  ken: "KE",
  kgz: "KG",
  kir: "KI",
  kor: "KR",
  kos: "XK",
  ksa: "SA",
  kuw: "KW",
  lao: "LA",
  lat: "LV",
  lba: "LY",
  lbn: "LB",
  lbr: "LR",
  lca: "LC",
  les: "LS",
  lie: "LI",
  ltu: "LT",
  lux: "LU",
  mac: "MO",
  mad: "MG",
  maf: "MF",
  mar: "MA",
  mas: "MY",
  maw: "MW",
  mda: "MD",
  mdv: "MV",
  mex: "MX",
  mgl: "MN",
  mhl: "MH",
  mkd: "MK",
  mli: "ML",
  mlt: "MT",
  mne: "ME",
  mnp: "MP",
  mon: "MC",
  moz: "MZ",
  mri: "MU",
  msr: "MS",
  mtn: "MR",
  mtq: "MQ",
  mya: "MM",
  myt: "YT",
  nam: "NA",
  nca: "NI",
  ncl: "NC",
  ned: "NL",
  nep: "NP",
  nfk: "NF",
  ngr: "NG",
  nig: "NE",
  niu: "NU",
  nor: "NO",
  nru: "NR",
  nzl: "NZ",
  oma: "OM",
  pak: "PK",
  pan: "PA",
  par: "PY",
  pcn: "PN",
  per: "PE",
  phi: "PH",
  ple: "PS",
  plw: "PW",
  png: "PG",
  pol: "PL",
  por: "PT",
  prk: "KP",
  pur: "PR",
  pyf: "PF",
  qat: "QA",
  reu: "RE",
  rou: "RO",
  rsa: "ZA",
  rus: "RU",
  rwa: "RW",
  sam: "WS",
  sen: "SN",
  sey: "SC",
  sgp: "SG",
  sgs: "GS",
  shn: "SH",
  sjm: "SJ",
  skn: "KN",
  sle: "SL",
  slo: "SI",
  smr: "SM",
  sol: "SB",
  som: "SO",
  spm: "PM",
  srb: "RS",
  sri: "LK",
  ssd: "SS",
  stp: "ST",
  sud: "SD",
  sui: "CH",
  sur: "SR",
  svk: "SK",
  swe: "SE",
  swz: "SZ",
  sxm: "SX",
  syr: "SY",
  tan: "TZ",
  tca: "TC",
  tga: "TO",
  tha: "TH",
  tjk: "TJ",
  tkl: "TK",
  tkm: "TM",
  tls: "TL",
  tog: "TG",
  tpe: "TW",
  tto: "TT",
  tun: "TN",
  tur: "TR",
  tuv: "TV",
  uae: "AE",
  uga: "UG",
  ukr: "UA",
  umi: "UM",
  uru: "UY",
  usa: "US",
  uzb: "UZ",
  van: "VU",
  vat: "VA",
  ven: "VE",
  vie: "VN",
  vin: "VC",
  wlf: "WF",
  yem: "YE",
  zam: "ZM",
  zim: "ZW",
  // Additional ISO codes retained alongside the IOC sporting codes.
  deu: "DE",
  nld: "NL",
  prt: "PT",
  che: "CH",
  grc: "GR",
  zaf: "ZA",
  npl: "NP",
  vnm: "VN",
  turkiye: "TR",
  türkiye: "TR",
  "antigua and barbuda": "AG",
  "antigua & barbuda": "AG",
  tahiti: "PF",
  "west bank": "PS",
  "saint helena": "SH",
  "st helena": "SH",
  "cote d'ivoire": "CI",
  "côte d'ivoire": "CI",
  "ivory coast": "CI",
  "chinese taipei": "TW",
  "hong kong china": "HK",
  "republic of korea": "KR",
  eire: "IE",
  britain: "GB",
  holland: "NL",
  macao: "MO",
  macau: "MO",
  uk: "GB",
  "great britain": "GB",
  british: "GB",
  "united kingdom": "GB",
  "united states of america": "US",
  "u.s.a.": "US",
  "republic of ireland": "IE",
  irish: "IE",
  american: "US",
  canadian: "CA",
  australian: "AU",
  "new zealander": "NZ",
  kenyan: "KE",
  ethiopian: "ET",
  ugandan: "UG",
  "south african": "ZA",
  french: "FR",
  german: "DE",
  spanish: "ES",
  portuguese: "PT",
  italian: "IT",
  dutch: "NL",
  swedish: "SE",
  norwegian: "NO",
  danish: "DK",
  finnish: "FI",
  polish: "PL",
  swiss: "CH",
  jamaican: "JM",
  japanese: "JP",
  chinese: "CN",
  indian: "IN",
  "czech republic": "CZ",
  "south korea": "KR",
  "north korea": "KP",
  turkey: "TR",
  "the netherlands": "NL",
};
export function countryFlag(value: string | null | undefined) {
  const original = value?.trim() ?? "";
  const key = original.normalize("NFKC").replace(/\s+/g, " ").toLowerCase();
  if (["world", "international", "und", "eur", "nac"].includes(key))
    return { code: "", name: "International", emoji: "🌐" };
  const home = (
    {
      england: "England",
      english: "England",
      eng: "England",
      "gb-eng": "England",
      scotland: "Scotland",
      scottish: "Scotland",
      sco: "Scotland",
      sct: "Scotland",
      "gb-sct": "Scotland",
      wales: "Wales",
      welsh: "Wales",
      wal: "Wales",
      wls: "Wales",
      "gb-wls": "Wales",
      "northern ireland": "Northern Ireland",
      nir: "Northern Ireland",
      "gb-nir": "Northern Ireland",
    } as Record<string, string>
  )[key];
  if (home)
    return {
      code:
        home === "England"
          ? "GB-ENG"
          : home === "Scotland"
            ? "GB-SCT"
            : home === "Wales"
              ? "GB-WLS"
              : "GB",
      name: home,
      emoji:
        home === "England"
          ? "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}"
          : home === "Scotland"
            ? "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}"
            : home === "Wales"
              ? "🏴\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}"
              : "🇬🇧",
    };
  const code = aliases[key] ?? regions.get(key);
  return {
    code: code ?? "",
    name: code ? (countryNames[code] ?? original) : original,
    emoji: code
      ? String.fromCodePoint(...[...code].map((letter) => letter.charCodeAt(0) + 127397))
      : "",
  };
}
