// Generated by scripts/generate-scraper-workbook-snapshot.py. Do not edit.
import part0 from "./scraper-workbook-snapshot-parts.server.generated/part-000";
import part1 from "./scraper-workbook-snapshot-parts.server.generated/part-001";
import part2 from "./scraper-workbook-snapshot-parts.server.generated/part-002";
import part3 from "./scraper-workbook-snapshot-parts.server.generated/part-003";
import part4 from "./scraper-workbook-snapshot-parts.server.generated/part-004";
import part5 from "./scraper-workbook-snapshot-parts.server.generated/part-005";
import part6 from "./scraper-workbook-snapshot-parts.server.generated/part-006";
import part7 from "./scraper-workbook-snapshot-parts.server.generated/part-007";
import part8 from "./scraper-workbook-snapshot-parts.server.generated/part-008";
import part9 from "./scraper-workbook-snapshot-parts.server.generated/part-009";
import part10 from "./scraper-workbook-snapshot-parts.server.generated/part-010";
import part11 from "./scraper-workbook-snapshot-parts.server.generated/part-011";
import part12 from "./scraper-workbook-snapshot-parts.server.generated/part-012";
import part13 from "./scraper-workbook-snapshot-parts.server.generated/part-013";
import part14 from "./scraper-workbook-snapshot-parts.server.generated/part-014";
import part15 from "./scraper-workbook-snapshot-parts.server.generated/part-015";
import part16 from "./scraper-workbook-snapshot-parts.server.generated/part-016";
import part17 from "./scraper-workbook-snapshot-parts.server.generated/part-017";
import part18 from "./scraper-workbook-snapshot-parts.server.generated/part-018";
import part19 from "./scraper-workbook-snapshot-parts.server.generated/part-019";
import part20 from "./scraper-workbook-snapshot-parts.server.generated/part-020";
import part21 from "./scraper-workbook-snapshot-parts.server.generated/part-021";
import part22 from "./scraper-workbook-snapshot-parts.server.generated/part-022";
import part23 from "./scraper-workbook-snapshot-parts.server.generated/part-023";
import part24 from "./scraper-workbook-snapshot-parts.server.generated/part-024";
import part25 from "./scraper-workbook-snapshot-parts.server.generated/part-025";
import part26 from "./scraper-workbook-snapshot-parts.server.generated/part-026";
import part27 from "./scraper-workbook-snapshot-parts.server.generated/part-027";

export const SCRAPER_WORKBOOK_SNAPSHOT_GZIP_BASE64 =
  [part0, part1, part2, part3, part4, part5, part6, part7, part8, part9, part10, part11, part12, part13, part14, part15, part16, part17, part18, part19, part20, part21, part22, part23, part24, part25, part26, part27].join("");
