/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AthletesIndexRouteImport } from './routes/athletes/index'
import { Route as AthletesSlugRouteImport } from './routes/athletes/$slug'
import { Route as ClubsIndexRouteImport } from './routes/clubs/index'
import { Route as ClubsSlugRouteImport } from './routes/clubs/$slug'
import { Route as RacesIndexRouteImport } from './routes/races/index'
import { Route as RacesSlugRouteImport } from './routes/races/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIndexRoute = AthletesIndexRouteImport.update({
  id: '/athletes/',
  path: '/athletes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesSlugRoute = AthletesSlugRouteImport.update({
  id: '/athletes/$slug',
  path: '/athletes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesSlugRoute = RacesSlugRouteImport.update({
  id: '/races/$slug',
  path: '/races/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/races/': typeof RacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/athletes': typeof AthletesIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/races': typeof RacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/races/': typeof RacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/athletes/$slug'
    | '/clubs/$slug'
    | '/races/$slug'
    | '/admin/'
    | '/athletes/'
    | '/clubs/'
    | '/races/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/athletes/$slug'
    | '/clubs/$slug'
    | '/races/$slug'
    | '/admin'
    | '/athletes'
    | '/clubs'
    | '/races'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/athletes/$slug'
    | '/clubs/$slug'
    | '/races/$slug'
    | '/admin/'
    | '/athletes/'
    | '/clubs/'
    | '/races/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  AthletesSlugRoute: typeof AthletesSlugRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  RacesSlugRoute: typeof RacesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthletesIndexRoute: typeof AthletesIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  RacesIndexRoute: typeof RacesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/': {
      id: '/athletes/'
      path: '/athletes'
      fullPath: '/athletes/'
      preLoaderRoute: typeof AthletesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$slug': {
      id: '/athletes/$slug'
      path: '/athletes/$slug'
      fullPath: '/athletes/$slug'
      preLoaderRoute: typeof AthletesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/$slug': {
      id: '/races/$slug'
      path: '/races/$slug'
      fullPath: '/races/$slug'
      preLoaderRoute: typeof RacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  AthletesSlugRoute: AthletesSlugRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  RacesSlugRoute: RacesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthletesIndexRoute: AthletesIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  RacesIndexRoute: RacesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
