/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AthleteAccountRouteImport } from './routes/athlete-account'
import { Route as AthleteResultsRouteImport } from './routes/athlete-results'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClaimResultsRouteImport } from './routes/claim-results'
import { Route as FindEventsRouteImport } from './routes/find-events'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MyAthleteProfileRouteImport } from './routes/my-athlete-profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RaceSeriesRouteImport } from './routes/race-series'
import { Route as ReviewResultsRouteImport } from './routes/review-results'
import { Route as SiteMapRouteImport } from './routes/site-map'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'
import { Route as SportsrecsRouteImport } from './routes/sportsrecs'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAthleteAccountsRouteImport } from './routes/admin/athlete-accounts'
import { Route as AdminAthleteDirectoryRouteImport } from './routes/admin/athlete-directory'
import { Route as AdminAthleteWorkspaceRouteImport } from './routes/admin/athlete-workspace'
import { Route as AdminCataloguePublishingRouteImport } from './routes/admin/catalogue-publishing'
import { Route as AdminCatalogueRecoveryEmergencyRouteImport } from './routes/admin/catalogue-recovery-emergency'
import { Route as AdminCheckResultsUploadRouteImport } from './routes/admin/check-results-upload'
import { Route as AdminClubScannerRouteImport } from './routes/admin/club-scanner'
import { Route as AdminDataIntelligenceRouteImport } from './routes/admin/data-intelligence'
import { Route as AdminFixtureReviewRouteImport } from './routes/admin/fixture-review'
import { Route as AdminNetworkRouteImport } from './routes/admin/network'
import { Route as AdminPartnershipsRouteImport } from './routes/admin/partnerships'
import { Route as AdminRaceCollectorRouteImport } from './routes/admin/race-collector'
import { Route as AdminResultArchiveRouteImport } from './routes/admin/result-archive'
import { Route as AdminResultClaimsRouteImport } from './routes/admin/result-claims'
import { Route as AdminResultLinksRouteImport } from './routes/admin/result-links'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as AdminSponsorshipRouteImport } from './routes/admin/sponsorship'
import { Route as ApiAthleteProfilePhotoRouteImport } from './routes/api/athlete-profile-photo'
import { Route as ApiCatalogueAutomationRouteImport } from './routes/api/catalogue-automation'
import { Route as ApiClubScannerWorkerRouteImport } from './routes/api/club-scanner-worker'
import { Route as ApiRaceCollectorWorkerRouteImport } from './routes/api/race-collector-worker'
import { Route as AthletesIndexRouteImport } from './routes/athletes/index'
import { Route as AthletesSlugRouteImport } from './routes/athletes/$slug'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as BrandsManageRouteImport } from './routes/brands/manage'
import { Route as BrandsRegisterRouteImport } from './routes/brands/register'
import { Route as ClubsIndexRouteImport } from './routes/clubs/index'
import { Route as ClubsSlugRouteImport } from './routes/clubs/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as RacesIndexRouteImport } from './routes/races/index'
import { Route as RacesSlugRouteImport } from './routes/races/$slug'
import { Route as ResultsIndexRouteImport } from './routes/results/index'
import { Route as ResultsEditionIdRouteImport } from './routes/results/$editionId'
import { Route as RunningIndexRouteImport } from './routes/running/index'
import { Route as RunningGuideRouteImport } from './routes/running/$guide'
import { Route as RunningUkMarathonsRouteImport } from './routes/running/uk-marathons'
import { Route as SitemapsFileRouteImport } from './routes/sitemaps/$file'
import { Route as SportsSportRouteImport } from './routes/sports/$sport'
import { Route as LanguageCountryIndexRouteImport } from './routes/$language/$country/index'
import { Route as AdminAthletesAthleteIdRouteImport } from './routes/admin/athletes.$athleteId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as RunningRacesSlugRouteImport } from './routes/running/races/$slug'
import { Route as LanguageCountryRacesIndexRouteImport } from './routes/$language/$country/races/index'
import { Route as LanguageCountryRacesSlugRouteImport } from './routes/$language/$country/races/$slug'
import { Route as ApiEventsSlugOfficialEntryRouteImport } from './routes/api/events/$slug/official-entry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteAccountRoute = AthleteAccountRouteImport.update({
  id: '/athlete-account',
  path: '/athlete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteResultsRoute = AthleteResultsRouteImport.update({
  id: '/athlete-results',
  path: '/athlete-results',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimResultsRoute = ClaimResultsRouteImport.update({
  id: '/claim-results',
  path: '/claim-results',
  getParentRoute: () => rootRouteImport,
} as any)
const FindEventsRoute = FindEventsRouteImport.update({
  id: '/find-events',
  path: '/find-events',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAthleteProfileRoute = MyAthleteProfileRouteImport.update({
  id: '/my-athlete-profile',
  path: '/my-athlete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceSeriesRoute = RaceSeriesRouteImport.update({
  id: '/race-series',
  path: '/race-series',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewResultsRoute = ReviewResultsRouteImport.update({
  id: '/review-results',
  path: '/review-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMapRoute = SiteMapRouteImport.update({
  id: '/site-map',
  path: '/site-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsrecsRoute = SportsrecsRouteImport.update({
  id: '/sportsrecs',
  path: '/sportsrecs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAthleteAccountsRoute = AdminAthleteAccountsRouteImport.update({
  id: '/admin/athlete-accounts',
  path: '/admin/athlete-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAthleteDirectoryRoute = AdminAthleteDirectoryRouteImport.update({
  id: '/admin/athlete-directory',
  path: '/admin/athlete-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAthleteWorkspaceRoute = AdminAthleteWorkspaceRouteImport.update({
  id: '/admin/athlete-workspace',
  path: '/admin/athlete-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCataloguePublishingRoute =
  AdminCataloguePublishingRouteImport.update({
    id: '/admin/catalogue-publishing',
    path: '/admin/catalogue-publishing',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCatalogueRecoveryEmergencyRoute =
  AdminCatalogueRecoveryEmergencyRouteImport.update({
    id: '/admin/catalogue-recovery-emergency',
    path: '/admin/catalogue-recovery-emergency',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCheckResultsUploadRoute = AdminCheckResultsUploadRouteImport.update({
  id: '/admin/check-results-upload',
  path: '/admin/check-results-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClubScannerRoute = AdminClubScannerRouteImport.update({
  id: '/admin/club-scanner',
  path: '/admin/club-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataIntelligenceRoute = AdminDataIntelligenceRouteImport.update({
  id: '/admin/data-intelligence',
  path: '/admin/data-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFixtureReviewRoute = AdminFixtureReviewRouteImport.update({
  id: '/admin/fixture-review',
  path: '/admin/fixture-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/admin/network',
  path: '/admin/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnershipsRoute = AdminPartnershipsRouteImport.update({
  id: '/admin/partnerships',
  path: '/admin/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRaceCollectorRoute = AdminRaceCollectorRouteImport.update({
  id: '/admin/race-collector',
  path: '/admin/race-collector',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultArchiveRoute = AdminResultArchiveRouteImport.update({
  id: '/admin/result-archive',
  path: '/admin/result-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultClaimsRoute = AdminResultClaimsRouteImport.update({
  id: '/admin/result-claims',
  path: '/admin/result-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultLinksRoute = AdminResultLinksRouteImport.update({
  id: '/admin/result-links',
  path: '/admin/result-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorshipRoute = AdminSponsorshipRouteImport.update({
  id: '/admin/sponsorship',
  path: '/admin/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAthleteProfilePhotoRoute = ApiAthleteProfilePhotoRouteImport.update({
  id: '/api/athlete-profile-photo',
  path: '/api/athlete-profile-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogueAutomationRoute = ApiCatalogueAutomationRouteImport.update({
  id: '/api/catalogue-automation',
  path: '/api/catalogue-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClubScannerWorkerRoute = ApiClubScannerWorkerRouteImport.update({
  id: '/api/club-scanner-worker',
  path: '/api/club-scanner-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRaceCollectorWorkerRoute = ApiRaceCollectorWorkerRouteImport.update({
  id: '/api/race-collector-worker',
  path: '/api/race-collector-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIndexRoute = AthletesIndexRouteImport.update({
  id: '/athletes/',
  path: '/athletes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesSlugRoute = AthletesSlugRouteImport.update({
  id: '/athletes/$slug',
  path: '/athletes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsManageRoute = BrandsManageRouteImport.update({
  id: '/brands/manage',
  path: '/brands/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRegisterRoute = BrandsRegisterRouteImport.update({
  id: '/brands/register',
  path: '/brands/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesSlugRoute = RacesSlugRouteImport.update({
  id: '/races/$slug',
  path: '/races/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsEditionIdRoute = ResultsEditionIdRouteImport.update({
  id: '/results/$editionId',
  path: '/results/$editionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningIndexRoute = RunningIndexRouteImport.update({
  id: '/running/',
  path: '/running/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningGuideRoute = RunningGuideRouteImport.update({
  id: '/running/$guide',
  path: '/running/$guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningUkMarathonsRoute = RunningUkMarathonsRouteImport.update({
  id: '/running/uk-marathons',
  path: '/running/uk-marathons',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsFileRoute = SitemapsFileRouteImport.update({
  id: '/sitemaps/$file',
  path: '/sitemaps/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportRoute = SportsSportRouteImport.update({
  id: '/sports/$sport',
  path: '/sports/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageCountryIndexRoute = LanguageCountryIndexRouteImport.update({
  id: '/$language/$country/',
  path: '/$language/$country/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAthletesAthleteIdRoute = AdminAthletesAthleteIdRouteImport.update({
  id: '/admin/athletes/$athleteId',
  path: '/admin/athletes/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRacesSlugRoute = RunningRacesSlugRouteImport.update({
  id: '/running/races/$slug',
  path: '/running/races/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageCountryRacesIndexRoute =
  LanguageCountryRacesIndexRouteImport.update({
    id: '/$language/$country/races/',
    path: '/$language/$country/races/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LanguageCountryRacesSlugRoute =
  LanguageCountryRacesSlugRouteImport.update({
    id: '/$language/$country/races/$slug',
    path: '/$language/$country/races/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEventsSlugOfficialEntryRoute =
  ApiEventsSlugOfficialEntryRouteImport.update({
    id: '/api/events/$slug/official-entry',
    path: '/api/events/$slug/official-entry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/athlete-account': typeof AthleteAccountRoute
  '/athlete-results': typeof AthleteResultsRoute
  '/calendar': typeof CalendarRoute
  '/claim-results': typeof ClaimResultsRoute
  '/find-events': typeof FindEventsRoute
  '/join': typeof JoinRoute
  '/my-athlete-profile': typeof MyAthleteProfileRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/race-series': typeof RaceSeriesRoute
  '/review-results': typeof ReviewResultsRoute
  '/site-map': typeof SiteMapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsorship': typeof SponsorshipRoute
  '/sportsrecs': typeof SportsrecsRoute
  '/admin/athlete-accounts': typeof AdminAthleteAccountsRoute
  '/admin/athlete-directory': typeof AdminAthleteDirectoryRoute
  '/admin/athlete-workspace': typeof AdminAthleteWorkspaceRoute
  '/admin/catalogue-publishing': typeof AdminCataloguePublishingRoute
  '/admin/catalogue-recovery-emergency': typeof AdminCatalogueRecoveryEmergencyRoute
  '/admin/check-results-upload': typeof AdminCheckResultsUploadRoute
  '/admin/club-scanner': typeof AdminClubScannerRoute
  '/admin/data-intelligence': typeof AdminDataIntelligenceRoute
  '/admin/fixture-review': typeof AdminFixtureReviewRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/race-collector': typeof AdminRaceCollectorRoute
  '/admin/result-archive': typeof AdminResultArchiveRoute
  '/admin/result-claims': typeof AdminResultClaimsRoute
  '/admin/result-links': typeof AdminResultLinksRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsorship': typeof AdminSponsorshipRoute
  '/api/athlete-profile-photo': typeof ApiAthleteProfilePhotoRoute
  '/api/catalogue-automation': typeof ApiCatalogueAutomationRoute
  '/api/club-scanner-worker': typeof ApiClubScannerWorkerRoute
  '/api/race-collector-worker': typeof ApiRaceCollectorWorkerRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/brands/manage': typeof BrandsManageRoute
  '/brands/register': typeof BrandsRegisterRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/results/$editionId': typeof ResultsEditionIdRoute
  '/running/$guide': typeof RunningGuideRoute
  '/running/uk-marathons': typeof RunningUkMarathonsRoute
  '/sitemaps/$file': typeof SitemapsFileRoute
  '/sports/$sport': typeof SportsSportRoute
  '/admin/': typeof AdminIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/races/': typeof RacesIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/running/': typeof RunningIndexRoute
  '/admin/athletes/$athleteId': typeof AdminAthletesAthleteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/running/races/$slug': typeof RunningRacesSlugRoute
  '/$language/$country/': typeof LanguageCountryIndexRoute
  '/$language/$country/races/$slug': typeof LanguageCountryRacesSlugRoute
  '/api/events/$slug/official-entry': typeof ApiEventsSlugOfficialEntryRoute
  '/$language/$country/races/': typeof LanguageCountryRacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/athlete-account': typeof AthleteAccountRoute
  '/athlete-results': typeof AthleteResultsRoute
  '/calendar': typeof CalendarRoute
  '/claim-results': typeof ClaimResultsRoute
  '/find-events': typeof FindEventsRoute
  '/join': typeof JoinRoute
  '/my-athlete-profile': typeof MyAthleteProfileRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/race-series': typeof RaceSeriesRoute
  '/review-results': typeof ReviewResultsRoute
  '/site-map': typeof SiteMapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsorship': typeof SponsorshipRoute
  '/sportsrecs': typeof SportsrecsRoute
  '/admin/athlete-accounts': typeof AdminAthleteAccountsRoute
  '/admin/athlete-directory': typeof AdminAthleteDirectoryRoute
  '/admin/athlete-workspace': typeof AdminAthleteWorkspaceRoute
  '/admin/catalogue-publishing': typeof AdminCataloguePublishingRoute
  '/admin/catalogue-recovery-emergency': typeof AdminCatalogueRecoveryEmergencyRoute
  '/admin/check-results-upload': typeof AdminCheckResultsUploadRoute
  '/admin/club-scanner': typeof AdminClubScannerRoute
  '/admin/data-intelligence': typeof AdminDataIntelligenceRoute
  '/admin/fixture-review': typeof AdminFixtureReviewRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/race-collector': typeof AdminRaceCollectorRoute
  '/admin/result-archive': typeof AdminResultArchiveRoute
  '/admin/result-claims': typeof AdminResultClaimsRoute
  '/admin/result-links': typeof AdminResultLinksRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsorship': typeof AdminSponsorshipRoute
  '/api/athlete-profile-photo': typeof ApiAthleteProfilePhotoRoute
  '/api/catalogue-automation': typeof ApiCatalogueAutomationRoute
  '/api/club-scanner-worker': typeof ApiClubScannerWorkerRoute
  '/api/race-collector-worker': typeof ApiRaceCollectorWorkerRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/brands/manage': typeof BrandsManageRoute
  '/brands/register': typeof BrandsRegisterRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/results/$editionId': typeof ResultsEditionIdRoute
  '/running/$guide': typeof RunningGuideRoute
  '/running/uk-marathons': typeof RunningUkMarathonsRoute
  '/sitemaps/$file': typeof SitemapsFileRoute
  '/sports/$sport': typeof SportsSportRoute
  '/admin': typeof AdminIndexRoute
  '/athletes': typeof AthletesIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/news': typeof NewsIndexRoute
  '/races': typeof RacesIndexRoute
  '/results': typeof ResultsIndexRoute
  '/running': typeof RunningIndexRoute
  '/admin/athletes/$athleteId': typeof AdminAthletesAthleteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/running/races/$slug': typeof RunningRacesSlugRoute
  '/$language/$country': typeof LanguageCountryIndexRoute
  '/$language/$country/races/$slug': typeof LanguageCountryRacesSlugRoute
  '/api/events/$slug/official-entry': typeof ApiEventsSlugOfficialEntryRoute
  '/$language/$country/races': typeof LanguageCountryRacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/athlete-account': typeof AthleteAccountRoute
  '/athlete-results': typeof AthleteResultsRoute
  '/calendar': typeof CalendarRoute
  '/claim-results': typeof ClaimResultsRoute
  '/find-events': typeof FindEventsRoute
  '/join': typeof JoinRoute
  '/my-athlete-profile': typeof MyAthleteProfileRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/race-series': typeof RaceSeriesRoute
  '/review-results': typeof ReviewResultsRoute
  '/site-map': typeof SiteMapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsorship': typeof SponsorshipRoute
  '/sportsrecs': typeof SportsrecsRoute
  '/admin/athlete-accounts': typeof AdminAthleteAccountsRoute
  '/admin/athlete-directory': typeof AdminAthleteDirectoryRoute
  '/admin/athlete-workspace': typeof AdminAthleteWorkspaceRoute
  '/admin/catalogue-publishing': typeof AdminCataloguePublishingRoute
  '/admin/catalogue-recovery-emergency': typeof AdminCatalogueRecoveryEmergencyRoute
  '/admin/check-results-upload': typeof AdminCheckResultsUploadRoute
  '/admin/club-scanner': typeof AdminClubScannerRoute
  '/admin/data-intelligence': typeof AdminDataIntelligenceRoute
  '/admin/fixture-review': typeof AdminFixtureReviewRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/race-collector': typeof AdminRaceCollectorRoute
  '/admin/result-archive': typeof AdminResultArchiveRoute
  '/admin/result-claims': typeof AdminResultClaimsRoute
  '/admin/result-links': typeof AdminResultLinksRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsorship': typeof AdminSponsorshipRoute
  '/api/athlete-profile-photo': typeof ApiAthleteProfilePhotoRoute
  '/api/catalogue-automation': typeof ApiCatalogueAutomationRoute
  '/api/club-scanner-worker': typeof ApiClubScannerWorkerRoute
  '/api/race-collector-worker': typeof ApiRaceCollectorWorkerRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/brands/manage': typeof BrandsManageRoute
  '/brands/register': typeof BrandsRegisterRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/results/$editionId': typeof ResultsEditionIdRoute
  '/running/$guide': typeof RunningGuideRoute
  '/running/uk-marathons': typeof RunningUkMarathonsRoute
  '/sitemaps/$file': typeof SitemapsFileRoute
  '/sports/$sport': typeof SportsSportRoute
  '/admin/': typeof AdminIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/races/': typeof RacesIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/running/': typeof RunningIndexRoute
  '/admin/athletes/$athleteId': typeof AdminAthletesAthleteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/running/races/$slug': typeof RunningRacesSlugRoute
  '/$language/$country/': typeof LanguageCountryIndexRoute
  '/$language/$country/races/$slug': typeof LanguageCountryRacesSlugRoute
  '/api/events/$slug/official-entry': typeof ApiEventsSlugOfficialEntryRoute
  '/$language/$country/races/': typeof LanguageCountryRacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/athlete-account'
    | '/athlete-results'
    | '/calendar'
    | '/claim-results'
    | '/find-events'
    | '/join'
    | '/my-athlete-profile'
    | '/opportunities'
    | '/privacy'
    | '/race-series'
    | '/review-results'
    | '/site-map'
    | '/sitemap.xml'
    | '/sponsorship'
    | '/sportsrecs'
    | '/admin/athlete-accounts'
    | '/admin/athlete-directory'
    | '/admin/athlete-workspace'
    | '/admin/catalogue-publishing'
    | '/admin/catalogue-recovery-emergency'
    | '/admin/check-results-upload'
    | '/admin/club-scanner'
    | '/admin/data-intelligence'
    | '/admin/fixture-review'
    | '/admin/network'
    | '/admin/partnerships'
    | '/admin/race-collector'
    | '/admin/result-archive'
    | '/admin/result-claims'
    | '/admin/result-links'
    | '/admin/sources'
    | '/admin/sponsorship'
    | '/api/athlete-profile-photo'
    | '/api/catalogue-automation'
    | '/api/club-scanner-worker'
    | '/api/race-collector-worker'
    | '/athletes/$slug'
    | '/brands/manage'
    | '/brands/register'
    | '/clubs/$slug'
    | '/news/$slug'
    | '/races/$slug'
    | '/results/$editionId'
    | '/running/$guide'
    | '/running/uk-marathons'
    | '/sitemaps/$file'
    | '/sports/$sport'
    | '/admin/'
    | '/athletes/'
    | '/brands/'
    | '/clubs/'
    | '/news/'
    | '/races/'
    | '/results/'
    | '/running/'
    | '/admin/athletes/$athleteId'
    | '/api/auth/$'
    | '/running/races/$slug'
    | '/$language/$country/'
    | '/$language/$country/races/$slug'
    | '/api/events/$slug/official-entry'
    | '/$language/$country/races/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/athlete-account'
    | '/athlete-results'
    | '/calendar'
    | '/claim-results'
    | '/find-events'
    | '/join'
    | '/my-athlete-profile'
    | '/opportunities'
    | '/privacy'
    | '/race-series'
    | '/review-results'
    | '/site-map'
    | '/sitemap.xml'
    | '/sponsorship'
    | '/sportsrecs'
    | '/admin/athlete-accounts'
    | '/admin/athlete-directory'
    | '/admin/athlete-workspace'
    | '/admin/catalogue-publishing'
    | '/admin/catalogue-recovery-emergency'
    | '/admin/check-results-upload'
    | '/admin/club-scanner'
    | '/admin/data-intelligence'
    | '/admin/fixture-review'
    | '/admin/network'
    | '/admin/partnerships'
    | '/admin/race-collector'
    | '/admin/result-archive'
    | '/admin/result-claims'
    | '/admin/result-links'
    | '/admin/sources'
    | '/admin/sponsorship'
    | '/api/athlete-profile-photo'
    | '/api/catalogue-automation'
    | '/api/club-scanner-worker'
    | '/api/race-collector-worker'
    | '/athletes/$slug'
    | '/brands/manage'
    | '/brands/register'
    | '/clubs/$slug'
    | '/news/$slug'
    | '/races/$slug'
    | '/results/$editionId'
    | '/running/$guide'
    | '/running/uk-marathons'
    | '/sitemaps/$file'
    | '/sports/$sport'
    | '/admin'
    | '/athletes'
    | '/brands'
    | '/clubs'
    | '/news'
    | '/races'
    | '/results'
    | '/running'
    | '/admin/athletes/$athleteId'
    | '/api/auth/$'
    | '/running/races/$slug'
    | '/$language/$country'
    | '/$language/$country/races/$slug'
    | '/api/events/$slug/official-entry'
    | '/$language/$country/races'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/athlete-account'
    | '/athlete-results'
    | '/calendar'
    | '/claim-results'
    | '/find-events'
    | '/join'
    | '/my-athlete-profile'
    | '/opportunities'
    | '/privacy'
    | '/race-series'
    | '/review-results'
    | '/site-map'
    | '/sitemap.xml'
    | '/sponsorship'
    | '/sportsrecs'
    | '/admin/athlete-accounts'
    | '/admin/athlete-directory'
    | '/admin/athlete-workspace'
    | '/admin/catalogue-publishing'
    | '/admin/catalogue-recovery-emergency'
    | '/admin/check-results-upload'
    | '/admin/club-scanner'
    | '/admin/data-intelligence'
    | '/admin/fixture-review'
    | '/admin/network'
    | '/admin/partnerships'
    | '/admin/race-collector'
    | '/admin/result-archive'
    | '/admin/result-claims'
    | '/admin/result-links'
    | '/admin/sources'
    | '/admin/sponsorship'
    | '/api/athlete-profile-photo'
    | '/api/catalogue-automation'
    | '/api/club-scanner-worker'
    | '/api/race-collector-worker'
    | '/athletes/$slug'
    | '/brands/manage'
    | '/brands/register'
    | '/clubs/$slug'
    | '/news/$slug'
    | '/races/$slug'
    | '/results/$editionId'
    | '/running/$guide'
    | '/running/uk-marathons'
    | '/sitemaps/$file'
    | '/sports/$sport'
    | '/admin/'
    | '/athletes/'
    | '/brands/'
    | '/clubs/'
    | '/news/'
    | '/races/'
    | '/results/'
    | '/running/'
    | '/admin/athletes/$athleteId'
    | '/api/auth/$'
    | '/running/races/$slug'
    | '/$language/$country/'
    | '/$language/$country/races/$slug'
    | '/api/events/$slug/official-entry'
    | '/$language/$country/races/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AthleteAccountRoute: typeof AthleteAccountRoute
  AthleteResultsRoute: typeof AthleteResultsRoute
  CalendarRoute: typeof CalendarRoute
  ClaimResultsRoute: typeof ClaimResultsRoute
  FindEventsRoute: typeof FindEventsRoute
  JoinRoute: typeof JoinRoute
  MyAthleteProfileRoute: typeof MyAthleteProfileRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PrivacyRoute: typeof PrivacyRoute
  RaceSeriesRoute: typeof RaceSeriesRoute
  ReviewResultsRoute: typeof ReviewResultsRoute
  SiteMapRoute: typeof SiteMapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorshipRoute: typeof SponsorshipRoute
  SportsrecsRoute: typeof SportsrecsRoute
  AdminAthleteAccountsRoute: typeof AdminAthleteAccountsRoute
  AdminAthleteDirectoryRoute: typeof AdminAthleteDirectoryRoute
  AdminAthleteWorkspaceRoute: typeof AdminAthleteWorkspaceRoute
  AdminCataloguePublishingRoute: typeof AdminCataloguePublishingRoute
  AdminCatalogueRecoveryEmergencyRoute: typeof AdminCatalogueRecoveryEmergencyRoute
  AdminCheckResultsUploadRoute: typeof AdminCheckResultsUploadRoute
  AdminClubScannerRoute: typeof AdminClubScannerRoute
  AdminDataIntelligenceRoute: typeof AdminDataIntelligenceRoute
  AdminFixtureReviewRoute: typeof AdminFixtureReviewRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminPartnershipsRoute: typeof AdminPartnershipsRoute
  AdminRaceCollectorRoute: typeof AdminRaceCollectorRoute
  AdminResultArchiveRoute: typeof AdminResultArchiveRoute
  AdminResultClaimsRoute: typeof AdminResultClaimsRoute
  AdminResultLinksRoute: typeof AdminResultLinksRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminSponsorshipRoute: typeof AdminSponsorshipRoute
  ApiAthleteProfilePhotoRoute: typeof ApiAthleteProfilePhotoRoute
  ApiCatalogueAutomationRoute: typeof ApiCatalogueAutomationRoute
  ApiClubScannerWorkerRoute: typeof ApiClubScannerWorkerRoute
  ApiRaceCollectorWorkerRoute: typeof ApiRaceCollectorWorkerRoute
  AthletesSlugRoute: typeof AthletesSlugRoute
  BrandsManageRoute: typeof BrandsManageRoute
  BrandsRegisterRoute: typeof BrandsRegisterRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  RacesSlugRoute: typeof RacesSlugRoute
  ResultsEditionIdRoute: typeof ResultsEditionIdRoute
  RunningGuideRoute: typeof RunningGuideRoute
  RunningUkMarathonsRoute: typeof RunningUkMarathonsRoute
  SitemapsFileRoute: typeof SitemapsFileRoute
  SportsSportRoute: typeof SportsSportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthletesIndexRoute: typeof AthletesIndexRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  RacesIndexRoute: typeof RacesIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  RunningIndexRoute: typeof RunningIndexRoute
  AdminAthletesAthleteIdRoute: typeof AdminAthletesAthleteIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RunningRacesSlugRoute: typeof RunningRacesSlugRoute
  LanguageCountryIndexRoute: typeof LanguageCountryIndexRoute
  LanguageCountryRacesSlugRoute: typeof LanguageCountryRacesSlugRoute
  ApiEventsSlugOfficialEntryRoute: typeof ApiEventsSlugOfficialEntryRoute
  LanguageCountryRacesIndexRoute: typeof LanguageCountryRacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-account': {
      id: '/athlete-account'
      path: '/athlete-account'
      fullPath: '/athlete-account'
      preLoaderRoute: typeof AthleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-results': {
      id: '/athlete-results'
      path: '/athlete-results'
      fullPath: '/athlete-results'
      preLoaderRoute: typeof AthleteResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-results': {
      id: '/claim-results'
      path: '/claim-results'
      fullPath: '/claim-results'
      preLoaderRoute: typeof ClaimResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-events': {
      id: '/find-events'
      path: '/find-events'
      fullPath: '/find-events'
      preLoaderRoute: typeof FindEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-athlete-profile': {
      id: '/my-athlete-profile'
      path: '/my-athlete-profile'
      fullPath: '/my-athlete-profile'
      preLoaderRoute: typeof MyAthleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race-series': {
      id: '/race-series'
      path: '/race-series'
      fullPath: '/race-series'
      preLoaderRoute: typeof RaceSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-results': {
      id: '/review-results'
      path: '/review-results'
      fullPath: '/review-results'
      preLoaderRoute: typeof ReviewResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-map': {
      id: '/site-map'
      path: '/site-map'
      fullPath: '/site-map'
      preLoaderRoute: typeof SiteMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportsrecs': {
      id: '/sportsrecs'
      path: '/sportsrecs'
      fullPath: '/sportsrecs'
      preLoaderRoute: typeof SportsrecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/athlete-accounts': {
      id: '/admin/athlete-accounts'
      path: '/admin/athlete-accounts'
      fullPath: '/admin/athlete-accounts'
      preLoaderRoute: typeof AdminAthleteAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/athlete-directory': {
      id: '/admin/athlete-directory'
      path: '/admin/athlete-directory'
      fullPath: '/admin/athlete-directory'
      preLoaderRoute: typeof AdminAthleteDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/athlete-workspace': {
      id: '/admin/athlete-workspace'
      path: '/admin/athlete-workspace'
      fullPath: '/admin/athlete-workspace'
      preLoaderRoute: typeof AdminAthleteWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue-publishing': {
      id: '/admin/catalogue-publishing'
      path: '/admin/catalogue-publishing'
      fullPath: '/admin/catalogue-publishing'
      preLoaderRoute: typeof AdminCataloguePublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue-recovery-emergency': {
      id: '/admin/catalogue-recovery-emergency'
      path: '/admin/catalogue-recovery-emergency'
      fullPath: '/admin/catalogue-recovery-emergency'
      preLoaderRoute: typeof AdminCatalogueRecoveryEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/check-results-upload': {
      id: '/admin/check-results-upload'
      path: '/admin/check-results-upload'
      fullPath: '/admin/check-results-upload'
      preLoaderRoute: typeof AdminCheckResultsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/club-scanner': {
      id: '/admin/club-scanner'
      path: '/admin/club-scanner'
      fullPath: '/admin/club-scanner'
      preLoaderRoute: typeof AdminClubScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-intelligence': {
      id: '/admin/data-intelligence'
      path: '/admin/data-intelligence'
      fullPath: '/admin/data-intelligence'
      preLoaderRoute: typeof AdminDataIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fixture-review': {
      id: '/admin/fixture-review'
      path: '/admin/fixture-review'
      fullPath: '/admin/fixture-review'
      preLoaderRoute: typeof AdminFixtureReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/admin/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partnerships': {
      id: '/admin/partnerships'
      path: '/admin/partnerships'
      fullPath: '/admin/partnerships'
      preLoaderRoute: typeof AdminPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/race-collector': {
      id: '/admin/race-collector'
      path: '/admin/race-collector'
      fullPath: '/admin/race-collector'
      preLoaderRoute: typeof AdminRaceCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/result-archive': {
      id: '/admin/result-archive'
      path: '/admin/result-archive'
      fullPath: '/admin/result-archive'
      preLoaderRoute: typeof AdminResultArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/result-claims': {
      id: '/admin/result-claims'
      path: '/admin/result-claims'
      fullPath: '/admin/result-claims'
      preLoaderRoute: typeof AdminResultClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/result-links': {
      id: '/admin/result-links'
      path: '/admin/result-links'
      fullPath: '/admin/result-links'
      preLoaderRoute: typeof AdminResultLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsorship': {
      id: '/admin/sponsorship'
      path: '/admin/sponsorship'
      fullPath: '/admin/sponsorship'
      preLoaderRoute: typeof AdminSponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/athlete-profile-photo': {
      id: '/api/athlete-profile-photo'
      path: '/api/athlete-profile-photo'
      fullPath: '/api/athlete-profile-photo'
      preLoaderRoute: typeof ApiAthleteProfilePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalogue-automation': {
      id: '/api/catalogue-automation'
      path: '/api/catalogue-automation'
      fullPath: '/api/catalogue-automation'
      preLoaderRoute: typeof ApiCatalogueAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/club-scanner-worker': {
      id: '/api/club-scanner-worker'
      path: '/api/club-scanner-worker'
      fullPath: '/api/club-scanner-worker'
      preLoaderRoute: typeof ApiClubScannerWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/race-collector-worker': {
      id: '/api/race-collector-worker'
      path: '/api/race-collector-worker'
      fullPath: '/api/race-collector-worker'
      preLoaderRoute: typeof ApiRaceCollectorWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/': {
      id: '/athletes/'
      path: '/athletes'
      fullPath: '/athletes/'
      preLoaderRoute: typeof AthletesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$slug': {
      id: '/athletes/$slug'
      path: '/athletes/$slug'
      fullPath: '/athletes/$slug'
      preLoaderRoute: typeof AthletesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/manage': {
      id: '/brands/manage'
      path: '/brands/manage'
      fullPath: '/brands/manage'
      preLoaderRoute: typeof BrandsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/register': {
      id: '/brands/register'
      path: '/brands/register'
      fullPath: '/brands/register'
      preLoaderRoute: typeof BrandsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/$slug': {
      id: '/races/$slug'
      path: '/races/$slug'
      fullPath: '/races/$slug'
      preLoaderRoute: typeof RacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$editionId': {
      id: '/results/$editionId'
      path: '/results/$editionId'
      fullPath: '/results/$editionId'
      preLoaderRoute: typeof ResultsEditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/': {
      id: '/running/'
      path: '/running'
      fullPath: '/running/'
      preLoaderRoute: typeof RunningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/$guide': {
      id: '/running/$guide'
      path: '/running/$guide'
      fullPath: '/running/$guide'
      preLoaderRoute: typeof RunningGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/uk-marathons': {
      id: '/running/uk-marathons'
      path: '/running/uk-marathons'
      fullPath: '/running/uk-marathons'
      preLoaderRoute: typeof RunningUkMarathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/$file': {
      id: '/sitemaps/$file'
      path: '/sitemaps/$file'
      fullPath: '/sitemaps/$file'
      preLoaderRoute: typeof SitemapsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sport': {
      id: '/sports/$sport'
      path: '/sports/$sport'
      fullPath: '/sports/$sport'
      preLoaderRoute: typeof SportsSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language/$country/': {
      id: '/$language/$country/'
      path: '/$language/$country'
      fullPath: '/$language/$country/'
      preLoaderRoute: typeof LanguageCountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/athletes/$athleteId': {
      id: '/admin/athletes/$athleteId'
      path: '/admin/athletes/$athleteId'
      fullPath: '/admin/athletes/$athleteId'
      preLoaderRoute: typeof AdminAthletesAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/races/$slug': {
      id: '/running/races/$slug'
      path: '/running/races/$slug'
      fullPath: '/running/races/$slug'
      preLoaderRoute: typeof RunningRacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language/$country/races/': {
      id: '/$language/$country/races/'
      path: '/$language/$country/races'
      fullPath: '/$language/$country/races/'
      preLoaderRoute: typeof LanguageCountryRacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language/$country/races/$slug': {
      id: '/$language/$country/races/$slug'
      path: '/$language/$country/races/$slug'
      fullPath: '/$language/$country/races/$slug'
      preLoaderRoute: typeof LanguageCountryRacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$slug/official-entry': {
      id: '/api/events/$slug/official-entry'
      path: '/api/events/$slug/official-entry'
      fullPath: '/api/events/$slug/official-entry'
      preLoaderRoute: typeof ApiEventsSlugOfficialEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AthleteAccountRoute: AthleteAccountRoute,
  AthleteResultsRoute: AthleteResultsRoute,
  CalendarRoute: CalendarRoute,
  ClaimResultsRoute: ClaimResultsRoute,
  FindEventsRoute: FindEventsRoute,
  JoinRoute: JoinRoute,
  MyAthleteProfileRoute: MyAthleteProfileRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PrivacyRoute: PrivacyRoute,
  RaceSeriesRoute: RaceSeriesRoute,
  ReviewResultsRoute: ReviewResultsRoute,
  SiteMapRoute: SiteMapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorshipRoute: SponsorshipRoute,
  SportsrecsRoute: SportsrecsRoute,
  AdminAthleteAccountsRoute: AdminAthleteAccountsRoute,
  AdminAthleteDirectoryRoute: AdminAthleteDirectoryRoute,
  AdminAthleteWorkspaceRoute: AdminAthleteWorkspaceRoute,
  AdminCataloguePublishingRoute: AdminCataloguePublishingRoute,
  AdminCatalogueRecoveryEmergencyRoute: AdminCatalogueRecoveryEmergencyRoute,
  AdminCheckResultsUploadRoute: AdminCheckResultsUploadRoute,
  AdminClubScannerRoute: AdminClubScannerRoute,
  AdminDataIntelligenceRoute: AdminDataIntelligenceRoute,
  AdminFixtureReviewRoute: AdminFixtureReviewRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminPartnershipsRoute: AdminPartnershipsRoute,
  AdminRaceCollectorRoute: AdminRaceCollectorRoute,
  AdminResultArchiveRoute: AdminResultArchiveRoute,
  AdminResultClaimsRoute: AdminResultClaimsRoute,
  AdminResultLinksRoute: AdminResultLinksRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminSponsorshipRoute: AdminSponsorshipRoute,
  ApiAthleteProfilePhotoRoute: ApiAthleteProfilePhotoRoute,
  ApiCatalogueAutomationRoute: ApiCatalogueAutomationRoute,
  ApiClubScannerWorkerRoute: ApiClubScannerWorkerRoute,
  ApiRaceCollectorWorkerRoute: ApiRaceCollectorWorkerRoute,
  AthletesSlugRoute: AthletesSlugRoute,
  BrandsManageRoute: BrandsManageRoute,
  BrandsRegisterRoute: BrandsRegisterRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  RacesSlugRoute: RacesSlugRoute,
  ResultsEditionIdRoute: ResultsEditionIdRoute,
  RunningGuideRoute: RunningGuideRoute,
  RunningUkMarathonsRoute: RunningUkMarathonsRoute,
  SitemapsFileRoute: SitemapsFileRoute,
  SportsSportRoute: SportsSportRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthletesIndexRoute: AthletesIndexRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  RacesIndexRoute: RacesIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  RunningIndexRoute: RunningIndexRoute,
  AdminAthletesAthleteIdRoute: AdminAthletesAthleteIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RunningRacesSlugRoute: RunningRacesSlugRoute,
  LanguageCountryIndexRoute: LanguageCountryIndexRoute,
  LanguageCountryRacesSlugRoute: LanguageCountryRacesSlugRoute,
  ApiEventsSlugOfficialEntryRoute: ApiEventsSlugOfficialEntryRoute,
  LanguageCountryRacesIndexRoute: LanguageCountryRacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
