/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthleteAccountRouteImport } from './routes/athlete-account'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClaimResultsRouteImport } from './routes/claim-results'
import { Route as MyAthleteProfileRouteImport } from './routes/my-athlete-profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RaceSeriesRouteImport } from './routes/race-series'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAthleteAccountsRouteImport } from './routes/admin/athlete-accounts'
import { Route as AdminCataloguePublishingRouteImport } from './routes/admin/catalogue-publishing'
import { Route as AdminCatalogueRecoveryEmergencyRouteImport } from './routes/admin/catalogue-recovery-emergency'
import { Route as AdminDataIntelligenceRouteImport } from './routes/admin/data-intelligence'
import { Route as AdminFixtureReviewRouteImport } from './routes/admin/fixture-review'
import { Route as AdminResultArchiveRouteImport } from './routes/admin/result-archive'
import { Route as AdminResultClaimsRouteImport } from './routes/admin/result-claims'
import { Route as AdminResultLinksRouteImport } from './routes/admin/result-links'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as ApiAthleteProfilePhotoRouteImport } from './routes/api/athlete-profile-photo'
import { Route as ApiCatalogueAutomationRouteImport } from './routes/api/catalogue-automation'
import { Route as AthletesIndexRouteImport } from './routes/athletes/index'
import { Route as AthletesSlugRouteImport } from './routes/athletes/$slug'
import { Route as ClubsIndexRouteImport } from './routes/clubs/index'
import { Route as ClubsSlugRouteImport } from './routes/clubs/$slug'
import { Route as RacesIndexRouteImport } from './routes/races/index'
import { Route as RacesSlugRouteImport } from './routes/races/$slug'
import { Route as LanguageCountryIndexRouteImport } from './routes/$language/$country/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LanguageCountryRacesIndexRouteImport } from './routes/$language/$country/races/index'
import { Route as LanguageCountryRacesSlugRouteImport } from './routes/$language/$country/races/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteAccountRoute = AthleteAccountRouteImport.update({
  id: '/athlete-account',
  path: '/athlete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimResultsRoute = ClaimResultsRouteImport.update({
  id: '/claim-results',
  path: '/claim-results',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAthleteProfileRoute = MyAthleteProfileRouteImport.update({
  id: '/my-athlete-profile',
  path: '/my-athlete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceSeriesRoute = RaceSeriesRouteImport.update({
  id: '/race-series',
  path: '/race-series',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAthleteAccountsRoute = AdminAthleteAccountsRouteImport.update({
  id: '/admin/athlete-accounts',
  path: '/admin/athlete-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCataloguePublishingRoute =
  AdminCataloguePublishingRouteImport.update({
    id: '/admin/catalogue-publishing',
    path: '/admin/catalogue-publishing',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCatalogueRecoveryEmergencyRoute =
  AdminCatalogueRecoveryEmergencyRouteImport.update({
    id: '/admin/catalogue-recovery-emergency',
    path: '/admin/catalogue-recovery-emergency',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDataIntelligenceRoute = AdminDataIntelligenceRouteImport.update({
  id: '/admin/data-intelligence',
  path: '/admin/data-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFixtureReviewRoute = AdminFixtureReviewRouteImport.update({
  id: '/admin/fixture-review',
  path: '/admin/fixture-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultArchiveRoute = AdminResultArchiveRouteImport.update({
  id: '/admin/result-archive',
  path: '/admin/result-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultClaimsRoute = AdminResultClaimsRouteImport.update({
  id: '/admin/result-claims',
  path: '/admin/result-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultLinksRoute = AdminResultLinksRouteImport.update({
  id: '/admin/result-links',
  path: '/admin/result-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAthleteProfilePhotoRoute = ApiAthleteProfilePhotoRouteImport.update({
  id: '/api/athlete-profile-photo',
  path: '/api/athlete-profile-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogueAutomationRoute = ApiCatalogueAutomationRouteImport.update({
  id: '/api/catalogue-automation',
  path: '/api/catalogue-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIndexRoute = AthletesIndexRouteImport.update({
  id: '/athletes/',
  path: '/athletes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesSlugRoute = AthletesSlugRouteImport.update({
  id: '/athletes/$slug',
  path: '/athletes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesIndexRoute = RacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesSlugRoute = RacesSlugRouteImport.update({
  id: '/races/$slug',
  path: '/races/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageCountryIndexRoute = LanguageCountryIndexRouteImport.update({
  id: '/$language/$country/',
  path: '/$language/$country/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageCountryRacesIndexRoute =
  LanguageCountryRacesIndexRouteImport.update({
    id: '/$language/$country/races/',
    path: '/$language/$country/races/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LanguageCountryRacesSlugRoute =
  LanguageCountryRacesSlugRouteImport.update({
    id: '/$language/$country/races/$slug',
    path: '/$language/$country/races/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athlete-account': typeof AthleteAccountRoute
  '/calendar': typeof CalendarRoute
  '/claim-results': typeof ClaimResultsRoute
  '/my-athlete-profile': typeof MyAthleteProfileRoute
  '/privacy': typeof PrivacyRoute
  '/race-series': typeof RaceSeriesRoute
  '/admin/athlete-accounts': typeof AdminAthleteAccountsRoute
  '/admin/catalogue-publishing': typeof AdminCataloguePublishingRoute
  '/admin/catalogue-recovery-emergency': typeof AdminCatalogueRecoveryEmergencyRoute
  '/admin/data-intelligence': typeof AdminDataIntelligenceRoute
  '/admin/fixture-review': typeof AdminFixtureReviewRoute
  '/admin/result-archive': typeof AdminResultArchiveRoute
  '/admin/result-claims': typeof AdminResultClaimsRoute
  '/admin/result-links': typeof AdminResultLinksRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/api/athlete-profile-photo': typeof ApiAthleteProfilePhotoRoute
  '/api/catalogue-automation': typeof ApiCatalogueAutomationRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/races/': typeof RacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$language/$country/': typeof LanguageCountryIndexRoute
  '/$language/$country/races/$slug': typeof LanguageCountryRacesSlugRoute
  '/$language/$country/races/': typeof LanguageCountryRacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athlete-account': typeof AthleteAccountRoute
  '/calendar': typeof CalendarRoute
  '/claim-results': typeof ClaimResultsRoute
  '/my-athlete-profile': typeof MyAthleteProfileRoute
  '/privacy': typeof PrivacyRoute
  '/race-series': typeof RaceSeriesRoute
  '/admin/athlete-accounts': typeof AdminAthleteAccountsRoute
  '/admin/catalogue-publishing': typeof AdminCataloguePublishingRoute
  '/admin/catalogue-recovery-emergency': typeof AdminCatalogueRecoveryEmergencyRoute
  '/admin/data-intelligence': typeof AdminDataIntelligenceRoute
  '/admin/fixture-review': typeof AdminFixtureReviewRoute
  '/admin/result-archive': typeof AdminResultArchiveRoute
  '/admin/result-claims': typeof AdminResultClaimsRoute
  '/admin/result-links': typeof AdminResultLinksRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/api/athlete-profile-photo': typeof ApiAthleteProfilePhotoRoute
  '/api/catalogue-automation': typeof ApiCatalogueAutomationRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/athletes': typeof AthletesIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/races': typeof RacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$language/$country': typeof LanguageCountryIndexRoute
  '/$language/$country/races/$slug': typeof LanguageCountryRacesSlugRoute
  '/$language/$country/races': typeof LanguageCountryRacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athlete-account': typeof AthleteAccountRoute
  '/calendar': typeof CalendarRoute
  '/claim-results': typeof ClaimResultsRoute
  '/my-athlete-profile': typeof MyAthleteProfileRoute
  '/privacy': typeof PrivacyRoute
  '/race-series': typeof RaceSeriesRoute
  '/admin/athlete-accounts': typeof AdminAthleteAccountsRoute
  '/admin/catalogue-publishing': typeof AdminCataloguePublishingRoute
  '/admin/catalogue-recovery-emergency': typeof AdminCatalogueRecoveryEmergencyRoute
  '/admin/data-intelligence': typeof AdminDataIntelligenceRoute
  '/admin/fixture-review': typeof AdminFixtureReviewRoute
  '/admin/result-archive': typeof AdminResultArchiveRoute
  '/admin/result-claims': typeof AdminResultClaimsRoute
  '/admin/result-links': typeof AdminResultLinksRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/api/athlete-profile-photo': typeof ApiAthleteProfilePhotoRoute
  '/api/catalogue-automation': typeof ApiCatalogueAutomationRoute
  '/athletes/$slug': typeof AthletesSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/races/$slug': typeof RacesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/races/': typeof RacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$language/$country/': typeof LanguageCountryIndexRoute
  '/$language/$country/races/$slug': typeof LanguageCountryRacesSlugRoute
  '/$language/$country/races/': typeof LanguageCountryRacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athlete-account'
    | '/calendar'
    | '/claim-results'
    | '/my-athlete-profile'
    | '/privacy'
    | '/race-series'
    | '/admin/athlete-accounts'
    | '/admin/catalogue-publishing'
    | '/admin/catalogue-recovery-emergency'
    | '/admin/data-intelligence'
    | '/admin/fixture-review'
    | '/admin/result-archive'
    | '/admin/result-claims'
    | '/admin/result-links'
    | '/admin/sources'
    | '/api/athlete-profile-photo'
    | '/api/catalogue-automation'
    | '/athletes/$slug'
    | '/clubs/$slug'
    | '/races/$slug'
    | '/admin/'
    | '/athletes/'
    | '/clubs/'
    | '/races/'
    | '/api/auth/$'
    | '/$language/$country/'
    | '/$language/$country/races/$slug'
    | '/$language/$country/races/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athlete-account'
    | '/calendar'
    | '/claim-results'
    | '/my-athlete-profile'
    | '/privacy'
    | '/race-series'
    | '/admin/athlete-accounts'
    | '/admin/catalogue-publishing'
    | '/admin/catalogue-recovery-emergency'
    | '/admin/data-intelligence'
    | '/admin/fixture-review'
    | '/admin/result-archive'
    | '/admin/result-claims'
    | '/admin/result-links'
    | '/admin/sources'
    | '/api/athlete-profile-photo'
    | '/api/catalogue-automation'
    | '/athletes/$slug'
    | '/clubs/$slug'
    | '/races/$slug'
    | '/admin'
    | '/athletes'
    | '/clubs'
    | '/races'
    | '/api/auth/$'
    | '/$language/$country'
    | '/$language/$country/races/$slug'
    | '/$language/$country/races'
  id:
    | '__root__'
    | '/'
    | '/athlete-account'
    | '/calendar'
    | '/claim-results'
    | '/my-athlete-profile'
    | '/privacy'
    | '/race-series'
    | '/admin/athlete-accounts'
    | '/admin/catalogue-publishing'
    | '/admin/catalogue-recovery-emergency'
    | '/admin/data-intelligence'
    | '/admin/fixture-review'
    | '/admin/result-archive'
    | '/admin/result-claims'
    | '/admin/result-links'
    | '/admin/sources'
    | '/api/athlete-profile-photo'
    | '/api/catalogue-automation'
    | '/athletes/$slug'
    | '/clubs/$slug'
    | '/races/$slug'
    | '/admin/'
    | '/athletes/'
    | '/clubs/'
    | '/races/'
    | '/api/auth/$'
    | '/$language/$country/'
    | '/$language/$country/races/$slug'
    | '/$language/$country/races/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthleteAccountRoute: typeof AthleteAccountRoute
  CalendarRoute: typeof CalendarRoute
  ClaimResultsRoute: typeof ClaimResultsRoute
  MyAthleteProfileRoute: typeof MyAthleteProfileRoute
  PrivacyRoute: typeof PrivacyRoute
  RaceSeriesRoute: typeof RaceSeriesRoute
  AdminAthleteAccountsRoute: typeof AdminAthleteAccountsRoute
  AdminCataloguePublishingRoute: typeof AdminCataloguePublishingRoute
  AdminCatalogueRecoveryEmergencyRoute: typeof AdminCatalogueRecoveryEmergencyRoute
  AdminDataIntelligenceRoute: typeof AdminDataIntelligenceRoute
  AdminFixtureReviewRoute: typeof AdminFixtureReviewRoute
  AdminResultArchiveRoute: typeof AdminResultArchiveRoute
  AdminResultClaimsRoute: typeof AdminResultClaimsRoute
  AdminResultLinksRoute: typeof AdminResultLinksRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  ApiAthleteProfilePhotoRoute: typeof ApiAthleteProfilePhotoRoute
  ApiCatalogueAutomationRoute: typeof ApiCatalogueAutomationRoute
  AthletesSlugRoute: typeof AthletesSlugRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  RacesSlugRoute: typeof RacesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthletesIndexRoute: typeof AthletesIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  RacesIndexRoute: typeof RacesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  LanguageCountryIndexRoute: typeof LanguageCountryIndexRoute
  LanguageCountryRacesSlugRoute: typeof LanguageCountryRacesSlugRoute
  LanguageCountryRacesIndexRoute: typeof LanguageCountryRacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-account': {
      id: '/athlete-account'
      path: '/athlete-account'
      fullPath: '/athlete-account'
      preLoaderRoute: typeof AthleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-results': {
      id: '/claim-results'
      path: '/claim-results'
      fullPath: '/claim-results'
      preLoaderRoute: typeof ClaimResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-athlete-profile': {
      id: '/my-athlete-profile'
      path: '/my-athlete-profile'
      fullPath: '/my-athlete-profile'
      preLoaderRoute: typeof MyAthleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race-series': {
      id: '/race-series'
      path: '/race-series'
      fullPath: '/race-series'
      preLoaderRoute: typeof RaceSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/athlete-accounts': {
      id: '/admin/athlete-accounts'
      path: '/admin/athlete-accounts'
      fullPath: '/admin/athlete-accounts'
      preLoaderRoute: typeof AdminAthleteAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue-publishing': {
      id: '/admin/catalogue-publishing'
      path: '/admin/catalogue-publishing'
      fullPath: '/admin/catalogue-publishing'
      preLoaderRoute: typeof AdminCataloguePublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue-recovery-emergency': {
      id: '/admin/catalogue-recovery-emergency'
      path: '/admin/catalogue-recovery-emergency'
      fullPath: '/admin/catalogue-recovery-emergency'
      preLoaderRoute: typeof AdminCatalogueRecoveryEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-intelligence': {
      id: '/admin/data-intelligence'
      path: '/admin/data-intelligence'
      fullPath: '/admin/data-intelligence'
      preLoaderRoute: typeof AdminDataIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fixture-review': {
      id: '/admin/fixture-review'
      path: '/admin/fixture-review'
      fullPath: '/admin/fixture-review'
      preLoaderRoute: typeof AdminFixtureReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/result-archive': {
      id: '/admin/result-archive'
      path: '/admin/result-archive'
      fullPath: '/admin/result-archive'
      preLoaderRoute: typeof AdminResultArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/result-claims': {
      id: '/admin/result-claims'
      path: '/admin/result-claims'
      fullPath: '/admin/result-claims'
      preLoaderRoute: typeof AdminResultClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/result-links': {
      id: '/admin/result-links'
      path: '/admin/result-links'
      fullPath: '/admin/result-links'
      preLoaderRoute: typeof AdminResultLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/athlete-profile-photo': {
      id: '/api/athlete-profile-photo'
      path: '/api/athlete-profile-photo'
      fullPath: '/api/athlete-profile-photo'
      preLoaderRoute: typeof ApiAthleteProfilePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalogue-automation': {
      id: '/api/catalogue-automation'
      path: '/api/catalogue-automation'
      fullPath: '/api/catalogue-automation'
      preLoaderRoute: typeof ApiCatalogueAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/': {
      id: '/athletes/'
      path: '/athletes'
      fullPath: '/athletes/'
      preLoaderRoute: typeof AthletesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$slug': {
      id: '/athletes/$slug'
      path: '/athletes/$slug'
      fullPath: '/athletes/$slug'
      preLoaderRoute: typeof AthletesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/': {
      id: '/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof RacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races/$slug': {
      id: '/races/$slug'
      path: '/races/$slug'
      fullPath: '/races/$slug'
      preLoaderRoute: typeof RacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language/$country/': {
      id: '/$language/$country/'
      path: '/$language/$country'
      fullPath: '/$language/$country/'
      preLoaderRoute: typeof LanguageCountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language/$country/races/': {
      id: '/$language/$country/races/'
      path: '/$language/$country/races'
      fullPath: '/$language/$country/races/'
      preLoaderRoute: typeof LanguageCountryRacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language/$country/races/$slug': {
      id: '/$language/$country/races/$slug'
      path: '/$language/$country/races/$slug'
      fullPath: '/$language/$country/races/$slug'
      preLoaderRoute: typeof LanguageCountryRacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthleteAccountRoute: AthleteAccountRoute,
  CalendarRoute: CalendarRoute,
  ClaimResultsRoute: ClaimResultsRoute,
  MyAthleteProfileRoute: MyAthleteProfileRoute,
  PrivacyRoute: PrivacyRoute,
  RaceSeriesRoute: RaceSeriesRoute,
  AdminAthleteAccountsRoute: AdminAthleteAccountsRoute,
  AdminCataloguePublishingRoute: AdminCataloguePublishingRoute,
  AdminCatalogueRecoveryEmergencyRoute: AdminCatalogueRecoveryEmergencyRoute,
  AdminDataIntelligenceRoute: AdminDataIntelligenceRoute,
  AdminFixtureReviewRoute: AdminFixtureReviewRoute,
  AdminResultArchiveRoute: AdminResultArchiveRoute,
  AdminResultClaimsRoute: AdminResultClaimsRoute,
  AdminResultLinksRoute: AdminResultLinksRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  ApiAthleteProfilePhotoRoute: ApiAthleteProfilePhotoRoute,
  ApiCatalogueAutomationRoute: ApiCatalogueAutomationRoute,
  AthletesSlugRoute: AthletesSlugRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  RacesSlugRoute: RacesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthletesIndexRoute: AthletesIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  RacesIndexRoute: RacesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LanguageCountryIndexRoute: LanguageCountryIndexRoute,
  LanguageCountryRacesSlugRoute: LanguageCountryRacesSlugRoute,
  LanguageCountryRacesIndexRoute: LanguageCountryRacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
