import { mkdir, copyFile, readFile } from "node:fs/promises";
import { Script } from "node:vm";
if (process.env.VERCEL_ENV === "production") throw new Error("This branch is a design preview and must not be deployed to production.");
const html = await readFile("design-preview/index.html", "utf8");
const script = html.split("<script>")[1]?.split("</script>")[0];
if (!script) throw new Error("Preview script missing");
new Script(script);
for (const marker of ["Countries", "Distances", "Surfaces", "requestFullscreen", 'data-view="rows"', 'data-view="cards"', 'data-view="table"', 'data-view="agenda"']) if (!html.includes(marker)) throw new Error("Missing " + marker);
await mkdir("design-preview/dist", { recursive: true });
await copyFile("design-preview/index.html", "design-preview/dist/index.html");
console.log("RunRecs standalone design preview built; four layouts and all selectors present.");
